format:
  html: {toc: true, toc-depth: 4, theme: darkly}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, chapter_01.qmd, chapter_02.qmd, chapter_03.qmd, chapter_04.qmd]
  favicon: notebooks/images/favicon.ico
